FROM python:3.8-slim-buster

ADD backend/requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

ADD backend /app/backend

WORKDIR /app/backend

ENTRYPOINT [ "python" ]

CMD [ "app.py" ]